[SendEmailTool]
resend = "*"

[CodeRunTool]
"langchain-experimental|langchain_experimental" = "==0.0.65"

[UncompressTool]
rarfile = "*"
bz2file = "*"

[TavilySearchTool]
rapidfuzz = "*"
requests-mock= "*"
pytest-mock = "*"

[PdfToImagesTool]
pypdfium2 = '*'





