[SendEmailTool]
resend = "*"

[CodeRunTool]
"langchain-experimental|langchain_experimental" = "*"

[UncompressTool]
rarfile = "*"
bz2file = "*"

[TavilySearchTool]
rapidfuzz = "*"
requests-mock= "*"
pytest-mock = "*"




