[SendEmailTool]
resend = "*"

[CodeRunTool]
"langchain-experimental|langchain_experimental" = "==0.0.65"

[UncompressTool]
rarfile = "*"
bz2file = "*"

[TavilySearchTool]
rapidfuzz = "*"
requests-mock= "*"
pytest-mock = "*"

[PdfToImagesTool]
pypdfium2 = '*'

[OcrTool]
filetype = "==1.2.0"
pypdfium2 = '*'
"pillow|PIL" = "*"

[CodbarTool]
pyzbar = '*'

[DockerTool]
docker = "*"





